url: https://cgw.institute
# baseurl: 



# Site settings
title: CGW Institute 
author: Discover / Design / Develop ~> Funding Proposals Made Easy
email: info @ license.academy
description: License Stack Apps


# Team names, titles and social links


#people:
#name: Raju Basumatary
#pic: 1
#position: Team Leader
#social:
#title: LinkedIn
#url: https://LinkedIn.com/in/digifaire


    #- title: facebook
    #  url: #
    #- title: stack-overflow
    #  url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social_links:
tiktok: licenseacademy
linkedin: licenseacademy
#social_links: 
social_links:
  #  - title: LinkedIn
  #  .fa-linkedin {
  #   url: https://www.linkedin.com/company/licenseacademy
  #   }
     
 # - title: facebook
 #   url:
 # - title: stack-overflow
 #   url: http://stackoverflow.com/questions/tagged/jekyll
 # - title: bitbucket 
 #   url: http://bitbucket.org/jekyll
 #   title: github
 #  url: https://github.com/digifaire

# Postal address (add as many lines as necessary)
# address:
# line: 1108 - 250 Consumers Road, #303, North York, ON M2J 4V6
#  - line: 

# Build settings
markdown: kramdown
permalink: pretty

